appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mv+0b/xpDWQ2rvvzcF2sQtBDhmn7OsEmuVpVd5V6Io6hy4d8aeV53nI8EXvyqR/3zK3o1HVDcGKiFQ3ZlYZWYcp/izABj6ujnFKve5G5pbDMLlsNLhz2EVjaap6A+19dUmKLtc/JQQE2t6bty/4pz1OnXM2E+5h8ZRi9zqNED9MZCqrW94tYaGFyENbBhF67I4eQgjU7xwJKa7RDSHpr7UHUMA0fGs9WU14NtOh/My50WHq2yFMwEuERj6PPjEwrm7YrqTUU8ABgjhWih0wl7/iLjBvmS6fCC0dBTpS8PXgnu+Iz+9wOYEFKFZHRVMnNuDc0tyzvx30ul3nvGS4xH8IdxkSXedsK9uoaE6SEmbzRa15MXzeJnfs2ktjbvQAeBDC7+3G1eclRCe+HN07m/HvyuyCZZO6oto7JsAC35Dxi2n56bZYD6Cy+eYqWK8x/5JI1rz3XHyRi4QfD9OdDP0QWRK0+bjmvOXNqVILXpculLxk6eoVpiTpprnqiR2eM5ENlNGIyPuuPh0CkMMqao7VmXRqBhbYSV6OrfS0zjeEvLg+46FFWoGoTxTye0ALWZN1aaVxEYwyd3uJcKHbY5v/tSI9PxmI+SxNCbw2oSJn2t1zVHgKHPIOfTwDu0AulzqpbQRZEM3whtAx9kq1bt223mpjizqPJ+GodW8L4798=}
